version: "3"

services:
  web-back:
    container_name: python-backend
    env_file: ./backend/web-back/.env
    build: ./backend/web-back/.
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=config.local_settings
    volumes:
      - ./backend/web-back:/code/
      - static_volume:/code/staticfiles
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 config.wsgi:application
    networks:
      - backend_network
    depends_on:
      - db
  backend-server:
    container_name: nginx-backend
    build:
      context: ./backend/nginx/.
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - static_volume:/code/staticfiles
    networks:
      - backend_network
    depends_on:
      - web-back
  db:
    container_name: postgres
    build: ./postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: launch_games_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./postgresql_volume/data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend_network
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - 5431:80
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@localhost.com
        PGADMIN_DEFAULT_PASSWORD: password
        TZ: Asia/Tokyo
    volumes:
      - ./pgadmin4_volume:/var/lib/pgadmin
    networks:
      - backend_network
    depends_on:
      - db
  web-front:
    container_name: web-frontend
    image: node:14.17.1
    ports:
      - 3000:3000
    volumes:
      - ./frontend/web-front:/home/app/frontend
    working_dir: /home/app/frontend
    command: [bash, -c, yarn upgrade --no-progress --network-timeout 1000000 && yarn run dev]
    networks:
      - frontend_network
  frontend-server:
    container_name: nginx-frontend
    build:
      context: ./frontend/nginx/.
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    networks:
      - frontend_network
    depends_on:
      - web-front
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
volumes:
  static_volume:
